---
abstract: ~
author:
  - 'Cornelius <cornelius.howl@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-I18N
no_index:
  directory:
    - examples
    - inc
    - share
    - t
requires:
  App::CLI: 0
  DBD::SQLite: 0
  DBI: 0
  DBIx::Class: 0
  Data::Dumper: 0
  Exporter: 0
  Exporter::Lite: 0
  File::Copy: 0
  File::Find::Rule: 0
  File::Path: 0
  File::ShareDir: 0
  Getopt::Long: 0
  JSON::XS: 0
  LWP::Simple: 0
  Locale::Language: 0
  Locale::Maketext::Extract: 0
  Locale::Maketext::Lexicon: 0
  MIME::Types: 0
  Plack: 0
  REST::Google::Translate: 0
  Tatsumaki: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
